steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/hello_npm', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/brodiem-demo/hello_npm"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - app
  - deploy
  - --quiet
  - --image-url=gcr.io/brodiem-demo/hello_npm
