steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/brodiemackenzie/gcb-cicd-demo']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/hello_npm', '.']
images: ['gcr.io/$PROJECT_ID/hello_npm']
