steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'flex-custom'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'flex-custom'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/hello_npm', '.']
  dir: 'flex-custom'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/hello_npm"]
  dir: 'flex-custom'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - app
  - deploy
  - --quiet
  - --image-url=gcr.io/$PROJECT_ID/hello_npm
  dir: 'flex-custom'
